language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

env:
  global:
  - secure: iw4v/jTy4kFMfOQCnuX9MCtGHVC6C+7Eks8FsDuZoQvIdCtMCJ77OL2dZEn6HJQiyIWqmKCsQKmY0kbvTNpmrXYrDwwMqvVnFWXC+5UWWYtCbhY7lfWIhcqFkPuD3CXytFP1a0w6bIqjdkwAibCxoz5vQ0NOTDa9ZQJXlsSgPLZxSHtNKXYamUYzUsDf4FslpyX8gZ4jJgvvhXRB7n7Rgnz4x/fwNUy4dtOdiHuQzcynwjaNLho6fEFTL0QSMNKXU7oF9/T6cI8Q0nGADDcIRJJAq7T+LX7AxYj8DoVfpoBRPZc8euluSGrC6Lf9++JdSv1JiVJkThlwHulxsZkmZBbRJ1RGf3eUVYZqmsrFkVrx9CRn9RauWc735/W8rAaNgBFyZuMLD6f/NmvIDvh85NCkhIy3hwaWMWeNvYuAR9e9qCr0PGIIrTFyFIYb7izGjeeAxZSx6TewBUEodeuh6CMH3dzU5CT8XMmCPOTClw+GALlABDTcjrbEgIILpQXM4AysFmwmJSgP4j+9vxVapB0IhMQTWslMcsvpw3VmK4S+Pw0EtMbGpH0a28YRJ8/ze0bgVZ4NLTYcHPc2mG3yG4msarGU3DRGIIPYA5PJ908BHue1SByTLVIysUMvL4fMg3l6rGaw+j5baiJisdeUOaFujb5uVFdoK/18yg8KbK8=
  - secure: FtLb7Sq9KhMB/owNZ+cPP601t7DIgMMvKD85inu6CIAibLfLZjK8zZZtUdV5Sa23+FEaRTcVu+S6CMrPiHD/EZ9ZcPaFZlQ+q60/9xm7luwmxn3EYpeGkAPKny/MOdBW35ZKXqsdoBQl80y6UZ4tnLoxPulT+7vakBfAQhwWxLaULFVeaX7ZA8+xPHAKjHPEVo4S8NUGj7lLtTLDjCsWBu1XRvCyzy1FIqoSBt86qdTBqgpSACQZFATNazyAJ1FnMBSxzrGZ79Qkx+PTYRvLZLcUAIymf0r2YA9W+ShJ61qx1LXWUKKMf8NQaC9f411/bMavyGl9tyJ57zfJ/tODTs5TT2TapafnvTUO6R0ylogdprGh47IuSpgUF1pKQ34j7G+aSiPKgQ15ZbT5sQ/IxLtD9cM/T/XUZtAXvI/TJ6H5ku6xmHW4wGMwUpYSfeI4XSGeh/oZG9kKe3rd07S8rcu/9PUxNBN6hBIhDKMxQT1T08+riIP4eZSg2IjX/Vubx6R4so346Miaql6XI+ihxRwdmFqCNLTwBheIM4AYoRrP3S0gc6cDQEpWXp5sHhn316hubUl2Y6WbLlHytTS9hhuUryU6hgZOFgyRw94iDj7XZOJJRk4bOoyMCFUfSEyXPV0l5DqTo6LMPPlmCM94y9OFUxPn4Rb7kAYl8LU5XFU=
