language: android

android:
  components:
    - tools
    - platform-tools

jdk:
  - oraclejdk8

# as per http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"

# script for build and release via Travis to Bintray
script: gradle/buildViaTravis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

env:
  global:
  - secure: fhD/i8FKEE5k2GSYZEs08lgCCS0wE7nHA3/AizEaatmlu3l1BckZ0nK3k8duQtizqP9xD5tl1KDehTKDc+3+d+Y/TS+3yaQPErLqavoswFxX4eFNH1g/csrau1HB78FEuQgdo2yt7gL8vda8QUTBFPhAcTuv0OQ7OKcBV4DX6xlZ94/2aV4b/rV+cxIy4qMQeRzLyxQR+2+rpC8d6vbbZaodVx8Xcu5O/WDNi2kYOr/mcfU3yH7FVmenfD91r9Szsc5/U72XwK4PlUduPosHIoFNsTsHm/yCBy8+ij3sA6WqPp/fqCBQbXJrUAUBxSRAqm5VTK1PKGew6YC7qEbiMGnah89Y2WQNkKr4yhAVe8v6rVZrr+wejikROnEkDI8GJShLEESbdFmO1DDkLmzegeMNzqZ/J3Zs6g0EKiQpWQZZvVXegkMd1mj3W/78vg2dH90uSVp4U5RQl273m6xD/zireamiayd/wYP6vHgcq6jdH5Sx9XgJBn2c/B0bgupezmAKX/1fH8X0OvT7ZNVVrM1XavN921xPN3HFZSXyLDz34Fy8em2YlDFglbMgO21l0Y9gdqTriKXWlMmjv0H+pMwyzjpCVUM8nQXW1mYlwTcwwkOr7Sbbcp0WThru0Te/0xzAh6LQ9KOMZbFVdH2vRfELOaQu/AMh1nff8knITK8=
  - secure: oEjQJ+P7KOmxq8RDOkKHFl+Hn53XELK7aJy63+tyT+hszeGFwEwZtiQvHS0pD71qwab0OTfQ7TqxH+po15sjeZ3NkXehCsjfGVWpAwMVkztyUAzA6jGqsqR3sAE2PXrm/U3hLZ5UaK/RVbULx7v0M5469Q9BY1I1TLuBrMggRFwdblJ0jYAO6SAFDLup13pciQZiAuFatuhxihcBaM88MRrhdF8rseXidhssrXus1MnLodPyUdnNljZP/jgHzhaOnc1+gSVm4OOv7xm9teLpodPRpLGb1uvBbKouIriyjuvQJ/6jlCymIk9NunQ009rLY4qHTkmNXa1VfxeQPjzLzWVEr15xwMkndYcv/zuL8Aw+jyl7LvoSGl34KPURUw/zfw5XCaaRqJFchkaZXmN9+pASMQoUm4596JPEp78D8a9PJR50yn2benuQffLOfUq003/BmI4p9z31Kz5MH4Yjpz86d+Chi3PbH2s70dIgNKwMu6pwCTwKOkZ6k1SNgNKf9VZMgzchh2hYXvQcQe9JgDryekrFgL7CZPEoftSWyRW01LQ75nT7VMFYYmwwm6sZP0sCaC8ZtfFvHI93lAN/4XYnpbvSC4Q2YQy6MFfcLZBCfBNNfsVpRiAF4MJ1RJWcxFdBumUbxgXqr4/y/wF/h4j7cvgKz3WFJdUP5P0o0Hk=
  - secure: HQM/bJTr7JhI3PejZlE3bMbZP6vIabr9hTkvUbLfONb5X/V41Wt3NfiILKmkM6yGw5JvTMariXIRBERL64rKnYAraPoaDaesFi9DhR+6tgKfvQkBp9KAc0XYJJPMIUcVidvj1z4AmVvVcL0DidLKJDV4ZD113NvoBERf9X/+Dzylm/5q5sM1OtDPy9NuqgsGnNP/swLhNmgEhZQieiQ48p4Wj8w8gd/+jpnxr1i9Co7EplsEisZBCY8wuA1IU4iRgV92mSO6Bz2ltrlHPedmrChmEEPvFDgdDOG4M+RJ6pC2mMzr0hlcYjtGrLa8W85kXoZhr71ebcEv6rMWT+guEPXuEK29M9j/vbQznkli7QuJbZNTzYDsK+xNYSA61timT9eHGpdMZ63IXZktBU3WElOyiBo+pbk7tkdk7s1NqmBlp79XZ4Q+6tsX+8TNLaPIa9Zp2r0LuiNhNreafT5Ih9J3iQPq7/AUL7XoyLBEVptENyUP6KhHDcbR2kIZdOUoiUqWQLIovftV9Thl7xJR+xG1Ub0J+SJEft9Qf2DM1HWjKWaitrnsSfic52u7SfWxDZWFrt5xLptyLAEDF5mSxW34guguSHzhkeBy9nvvpxLm65h/Vr14yQfQ5hSsrgE/+9eyO7a4xe88y3N8QUE325K14a1ux0qA9oNE0MdAchc=
